services:
  iut_abeille:
    container_name: iut_abeille
    image: node:lts
    env_file: ./service/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/api:/usr/src/app
    ports:
      - 3535:3000
    command: npm run watch
    depends_on:
      - iut_db_abeille
    links:
      - iut_db_abeille
    networks:
      - abeille

  iut_adminer_abeille:
    container_name: iut_adminer_abeille
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - iut_db_abeille
    networks:
      - abeille

  iut_db_abeille:
    container_name: iut_db_abeille
    image: mariadb:latest
    env_file: ./service/.env
    volumes:
      - ./service/db:/var/lib/mysql
      - ./service/snap_bee.sql:/docker-entrypoint-initdb.d/1.sql
 #     - ./service/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - abeille

networks:
  abeille:
    driver: bridge